/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DFileIdRouteImport } from './routes/d.$fileId'
import { Route as ApiManifestFileIdRouteImport } from './routes/api.manifest.$fileId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DFileIdRoute = DFileIdRouteImport.update({
  id: '/d/$fileId',
  path: '/d/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManifestFileIdRoute = ApiManifestFileIdRouteImport.update({
  id: '/api/manifest/$fileId',
  path: '/api/manifest/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/d/$fileId': typeof DFileIdRoute
  '/api/manifest/$fileId': typeof ApiManifestFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/d/$fileId': typeof DFileIdRoute
  '/api/manifest/$fileId': typeof ApiManifestFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/d/$fileId': typeof DFileIdRoute
  '/api/manifest/$fileId': typeof ApiManifestFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/d/$fileId' | '/api/manifest/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/d/$fileId' | '/api/manifest/$fileId'
  id: '__root__' | '/' | '/dashboard' | '/d/$fileId' | '/api/manifest/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DFileIdRoute: typeof DFileIdRoute
  ApiManifestFileIdRoute: typeof ApiManifestFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$fileId': {
      id: '/d/$fileId'
      path: '/d/$fileId'
      fullPath: '/d/$fileId'
      preLoaderRoute: typeof DFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manifest/$fileId': {
      id: '/api/manifest/$fileId'
      path: '/api/manifest/$fileId'
      fullPath: '/api/manifest/$fileId'
      preLoaderRoute: typeof ApiManifestFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DFileIdRoute: DFileIdRoute,
  ApiManifestFileIdRoute: ApiManifestFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
